import { isTooLarge, isGenerated, langOf, MAX_INDEX_BYTES } from './index-filter';

describe('isTooLarge', () => {
  it('상한은 열람의 512KB 가 아니라 256KB 다', () => {
    expect(MAX_INDEX_BYTES).toBe(256 * 1024);
  });

  it('상한과 같으면 통과, 넘으면 거른다', () => {
    expect(isTooLarge(MAX_INDEX_BYTES)).toBe(false);
    expect(isTooLarge(MAX_INDEX_BYTES + 1)).toBe(true);
  });
});

describe('isGenerated', () => {
  it('Dart 코드젠의 표시를 잡는다', () => {
    expect(isGenerated('// GENERATED CODE - DO NOT MODIFY BY HAND\npart of ...')).toBe(true);
  });

  it('널리 쓰이는 @generated 표시도 잡는다', () => {
    expect(isGenerated('/* @generated by protoc */\n')).toBe(true);
  });

  it('둘째 줄에 있어도 잡는다', () => {
    expect(isGenerated('#!/usr/bin/env node\n// @generated\nconst a = 1;')).toBe(true);
  });

  it('셋째 줄부터는 보지 않는다 — 본문에 그 말이 나오는 글까지 버리면 안 된다', () => {
    expect(isGenerated('a\nb\n// GENERATED CODE\n')).toBe(false);
  });

  it('사람이 쓴 코드는 통과시킨다', () => {
    expect(isGenerated('import { Injectable } from "@nestjs/common";\n')).toBe(false);
  });
});

describe('langOf', () => {
  it('확장자로 정한다', () => {
    expect(langOf('server/src/main.ts')).toBe('typescript');
    expect(langOf('app/lib/main.dart')).toBe('dart');
    expect(langOf('README.md')).toBe('markdown');
  });

  it('모르면 null 이다 — 억지로 채우지 않는다', () => {
    expect(langOf('LICENSE')).toBeNull();
    expect(langOf('a/b/.gitignore')).toBeNull();
  });

  it('대문자 확장자도 같게 본다', () => {
    expect(langOf('A.TS')).toBe('typescript');
  });
});
